
package service.client.jaxws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServiceFeux", targetNamespace = "http://Services.hub.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceFeux {


    /**
     * 
     * @param name
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFeuxTemp", targetNamespace = "http://Services.hub.service/", className = "service.client.jaxws.GetFeuxTemp")
    @ResponseWrapper(localName = "getFeuxTempResponse", targetNamespace = "http://Services.hub.service/", className = "service.client.jaxws.GetFeuxTempResponse")
    @Action(input = "http://Services.hub.service/ServiceFeux/getFeuxTempRequest", output = "http://Services.hub.service/ServiceFeux/getFeuxTempResponse")
    public int getFeuxTemp(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param name
     * @param feux
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setFeuxTemp", targetNamespace = "http://Services.hub.service/", className = "service.client.jaxws.SetFeuxTemp")
    @ResponseWrapper(localName = "setFeuxTempResponse", targetNamespace = "http://Services.hub.service/", className = "service.client.jaxws.SetFeuxTempResponse")
    @Action(input = "http://Services.hub.service/ServiceFeux/setFeuxTempRequest", output = "http://Services.hub.service/ServiceFeux/setFeuxTempResponse")
    public boolean setFeuxTemp(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "feux", targetNamespace = "")
        int feux);

}
