
package service.client.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServiceFeux", targetNamespace = "http://Services.hub.service/", wsdlLocation = "http://localhost:8081/ServiceFeux?wsdl")
public class ServiceFeux_Service
    extends Service
{

    private final static URL SERVICEFEUX_WSDL_LOCATION;
    private final static WebServiceException SERVICEFEUX_EXCEPTION;
    private final static QName SERVICEFEUX_QNAME = new QName("http://Services.hub.service/", "ServiceFeux");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ServiceFeux?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEFEUX_WSDL_LOCATION = url;
        SERVICEFEUX_EXCEPTION = e;
    }

    public ServiceFeux_Service() {
        super(__getWsdlLocation(), SERVICEFEUX_QNAME);
    }

    public ServiceFeux_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEFEUX_QNAME, features);
    }

    public ServiceFeux_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICEFEUX_QNAME);
    }

    public ServiceFeux_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEFEUX_QNAME, features);
    }

    public ServiceFeux_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceFeux_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceFeux
     */
    @WebEndpoint(name = "ServiceFeuxPort")
    public ServiceFeux getServiceFeuxPort() {
        return super.getPort(new QName("http://Services.hub.service/", "ServiceFeuxPort"), ServiceFeux.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceFeux
     */
    @WebEndpoint(name = "ServiceFeuxPort")
    public ServiceFeux getServiceFeuxPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services.hub.service/", "ServiceFeuxPort"), ServiceFeux.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEFEUX_EXCEPTION!= null) {
            throw SERVICEFEUX_EXCEPTION;
        }
        return SERVICEFEUX_WSDL_LOCATION;
    }

}
