package com.smartcity.traffic.api;

import com.smartcity.traffic.dto.AlertResponse;
import com.smartcity.traffic.model.Alert;
import com.smartcity.traffic.repository.AlertRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.sql.SQLException;
import java.util.List;
import java.util.stream.Collectors;

@Path("/api/alerts")
@Produces(MediaType.APPLICATION_JSON)
public class AlertResource {
    private static final Logger logger = LoggerFactory.getLogger(AlertResource.class);
    private final AlertRepository alertRepository;

    public AlertResource() {
        this.alertRepository = new AlertRepository();
    }

    /**
     * GET /api/alerts
     * Returns current or recent alerts generated by the central analysis system
     */
    @GET
    public Response getAlerts() {
        try {
            List<Alert> alerts = alertRepository.findActiveAlerts();
            
            List<AlertResponse> response = alerts.stream()
                    .map(AlertResponse::fromAlert)
                    .collect(Collectors.toList());

            return Response.ok(response).build();
            
        } catch (SQLException e) {
            logger.error("Error fetching alerts", e);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity("{\"error\": \"Internal server error\"}")
                    .build();
        }
    }
}
