package com.smartcity.traffic.api;

import com.smartcity.traffic.dto.RecommendationResponse;
import com.smartcity.traffic.model.Recommendation;
import com.smartcity.traffic.repository.RecommendationRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.sql.SQLException;
import java.util.List;
import java.util.stream.Collectors;

@Path("/api/recommendations")
@Produces(MediaType.APPLICATION_JSON)
public class RecommendationResource {
    private static final Logger logger = LoggerFactory.getLogger(RecommendationResource.class);
    private final RecommendationRepository recommendationRepository;

    public RecommendationResource() {
        this.recommendationRepository = new RecommendationRepository();
    }

    /**
     * GET /api/recommendations
     * Returns latest recommendations generated by the system
     */
    @GET
    public Response getRecommendations() {
        try {
            List<Recommendation> recommendations = recommendationRepository.findLatest(50);
            
            List<RecommendationResponse> response = recommendations.stream()
                    .map(RecommendationResponse::fromRecommendation)
                    .collect(Collectors.toList());

            return Response.ok(response).build();
            
        } catch (SQLException e) {
            logger.error("Error fetching recommendations", e);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity("{\"error\": \"Internal server error\"}")
                    .build();
        }
    }
}
